target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'shared', :path => '../shared'
# TODO: chech version after updating gitlive firebase
  pod 'FirebaseAnalytics', '11.8.0'
  pod 'FirebasePerformance', '11.8.0'
  pod 'FirebaseMessaging', '11.8.0'
  pod 'FirebaseAuth', '11.8.0'
#   pod 'YandexMobileAds', '6.4.1'
end
