target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'shared', :path => '../shared'
  pod 'FirebaseAnalytics', '10.18.0'
  pod 'FirebasePerformance', '10.19.0'
  pod 'YandexMobileAds', '6.4.1'
end
