name: Build

on:
  pull_request:
    branches: [ "master" ]

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Detekt
      run: ./gradlew detekt

    - name: Android Build with Gradle
      run: ./gradlew build --exclude-task :androidApp:processDebugGoogleServices --exclude-task :androidApp:processReleaseGoogleServices

    - name: Upload Gradle problems report
      uses: actions/upload-artifact@v4
      with:
        name: gradle-problems-report
        path: build/reports/problems/problems-report.html
#    - name: IOS build TODO

#    - name: Run test
#      run: ./gradlew allTests
