name: Build

on:
  pull_request:
    branches:
      - .*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Detekt
      run: ./gradlew detekt

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: ./gradlew build
    - uses: sparkfabrik/ios-build-action@v2.3.2

    - name: Run test
      run: ./gradlew allTests
